server:
  port: 8001

spring:
  datasource:
    url: jdbc:mysql://114.55.145.3:3306/mangostreet?characterEncoding=utf-8&useSSL=false
    username: root
    password: wjyy26303
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000
      connection-test-query: SELECT 1

  jpa:
#    hibernate:
#      ddl-auto: update
    show-sql: true